In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [35]:
df = pd.read_csv('data copy.csv')
df

Id Colour Country
0    1    Red     USA
1    2   Blue      UK
2    3  Green  Canada
3    4   Blue     USA
4    5   Blue     USA
5    6    Red  Canada
6    7  Green      UK
7    8    Red  Canada
8    9  Green      UK
9   10  Green      UK
10  11    Red  Canada
11  12    Red  Canada

In [4]:
df.dtypes

Id          int64
Colour     object
Country    object
dtype: object

In [9]:
df['Colour'].unique()

array(['Red', 'Blue', 'Green'], dtype=object)

In [37]:
df['Country'].unique()

array(['USA', 'UK', 'Canada'], dtype=object)

In [11]:
ohe = OneHotEncoder()

In [12]:
print(ohe)

OneHotEncoder()


In [28]:
feature_array = ohe.fit_transform(df[['Colour', 'Country']]).toarray()
print(feature_array)

[[0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]


In [16]:
ohe.categories_

[array(['Blue', 'Green', 'Red'], dtype=object),
 array(['Canada', 'UK', 'USA'], dtype=object)]

In [29]:
feature_labels = ohe.categories_

In [30]:
np.array(feature_labels).ravel()

array(['Blue', 'Green', 'Red', 'Canada', 'UK', 'USA'], dtype=object)

In [31]:
feature_label = np.array(feature_labels).ravel()
print(feature_label)

['Blue' 'Green' 'Red' 'Canada' 'UK' 'USA']


In [32]:
feature = pd.DataFrame(feature_array,columns = feature_label)


In [34]:
df_new = pd.concat([df,feature],axis=1)
df_new

Id Colour Country  Blue  Green  Red  Canada   UK  USA
0    1    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
1    2   Blue      UK   1.0    0.0  0.0     0.0  1.0  0.0
2    3  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
3    4   Blue     USA   1.0    0.0  0.0     0.0  0.0  1.0
4    5   Blue     USA   1.0    0.0  0.0     0.0  0.0  1.0
5    6    Red  Canada   0.0    0.0  1.0     1.0  0.0  0.0
6    7  Green      UK   0.0    1.0  0.0     0.0  1.0  0.0
7    8    Red  Canada   0.0    0.0  1.0     1.0  0.0  0.0
8    9  Green      UK   0.0    1.0  0.0     0.0  1.0  0.0
9   10  Green      UK   0.0    1.0  0.0     0.0  1.0  0.0
10  11    Red  Canada   0.0    0.0  1.0     1.0  0.0  0.0
11  12    Red  Canada   0.0    0.0  1.0     1.0  0.0  0.0